language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
    - "python setup.py develop"
    - "pip install mirakuru[tests] coveralls pylama"
script:
    - "py.test -v --cov mirakuru"
    - pylama
after_success:
    - coveralls
