language: python
sudo: false
matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      language: generic
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy-5.3.1
    - os: linux
      python: pypy3.5-5.8.0
# blocklist branches
branches:
  except:
  - requires-io-master
before_install:
  # Perform the manual steps on osx to install python3 and activate venv
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip install "setuptools>=21"
  - pip install "pip>=9"
  - pip install -r requirements-test.txt
  - python setup.py develop
  - pip install mirakuru[tests]
  # rst files verifier, and pygments to parse code-blocks
  - pip install coveralls wheel
script:
  - pytest -vvv --capture=no --showlocals --cov mirakuru tests/
  - pylama
  - rst-lint *.rst
after_success:
  - coveralls
deploy:
  provider: pypi
  user: fizyk
  password:
    secure: IBVXG0zLKsBkzdeoC33Lxir01jbvDHdjQ81CPC8PbDPCmUozXgf9eqRFV5VOIYQOboTBzQYRq7RB8efeNKSH3nKf73iahwIYf4ezIxRzUaMzoY4GkyrC/0fQhMk1lAjexrRM1f2o7TIAALPUDyB/EaRcPCBEghxscQEeTlAw08c=
  on:
    tags: true
    all_branches: true
    repo: ClearcodeHQ/mirakuru
    python: 3.6
  distributions: sdist bdist_wheel
