language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
    - "python setup.py develop"
    - "pip install mirakuru[tests] coveralls"
script:
    - "py.test -v  --cov mirakuru"
after_success:
    - coveralls
