name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v3.0.0
    with:
      pre-commit: true
