name: Run tests on macos

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - .github/workflows/tests-macos.yml
      - requirements-test.txt
  pull_request:
    branches: [ main ]

jobs:
  macostests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.6.4
    with:
      pipenv: true
      pipenv-install-options: "--skip-lock"
      python-versions: '["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]'
      os: macos-latest
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
